name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      
      # Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      
      # Build website
      - name: Build website
        run: bundle exec jekyll build --destination _site
      
      # Deploy to Cloudflare Pages
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy _site --project-name=vatis-website
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}